### ISSUE TITLE
Add support to doc block comments

### ISSUE THREAD

**Issue by fsmaia** [oskarols/foldcomments#10]
With the advent of tools like JSDoc and YUIDoc, should be interesting to differentiate docblock comments (in my conception, starting with '/**', single or multiline); and add settings to fold each type of comments (singleline, multiline or docblock).

**Comment by 20Tauri** [comment]
Oskar, I don't know if your are interested in adding this specific feature...

@fsmaia I'm the author of [DoxyDoxygen], this plugin manage "docblocks" and can "fold" them... It can be used in addition of FoldComments (no conflict). There's no direct shortcut to fold/untold (you will have to use the palette), but can be added easily with those both commands
```python
view.run_command("doxy_select_comments", {"kind": "doxy"}) # "doxy" mean "docblock"
view.run_command("doxy_fold_comments", {"action": "toggle"}) # or "fold", "unfold"
```
Hope will help
[DoxyDoxygen]: https://github.com/20Tauri/DoxyDoxygen

**Comment by fsmaia** [comment]
Hi!

Congratz, really nice!

Have you checked my [PR](https://github.com/oskarols/foldcomments/pull/11)?

I thought it was able to do the job, but instead of specific actions, I chose to specify fold/unfold behavior through the following settings:

- fold_single_line_comments
- fold_multi_line_comments
- fold_doc_block_comments

Do you prefer a specific action instead?

Big thanks so far!

**Comment by oskarols** [comment]
Sorry for showing up tremendously late!
Your approach is fine, so I merged it :)

Haven't been using Sublime for a while now, but I'll keep supporting this.
