### ISSUE TITLE
Don't fold short comments

### ISSUE THREAD

**Issue by madbarron** [oskarols/foldcomments#7]
It is silly to fold a single-line comment, as it doesn't shrink and just becomes unreadable. It would be nice to have the command not fold one-liners by default, and maybe allow an option in the preferences for minimum # of lines that a comment has to be in order to be folded.

**Comment by oskarols** [comment]
Hi @madbarron 

There is a configuration parameter you could override for not folding single line comments.

There is however some issues with "multi-line" single-line comments, i.e:
```
// a comment 
// another comment
// all the comments
```
Sometimes being tagged by ST as a multi-line comment, and sometimes it's a single-line — seemingly depending on the scope.

Try the configuration parameter and get back to me. I'm also very open to PRs, the code should be fairly easy to figure out.

**Comment by madbarron** [comment]
What is the configuration parameter I should use? I can't find anything about that.

**Comment by oskarols** [comment]
@madbarron You should be able to see the specific configuration parameters by going to `Preferences` -> `Package Settings` -> `Fold Comments` -> `Fold Comments Settings — User`

Then you can either override those parameters, or change it in your User Setting file.

**Comment by madbarron** [comment]
Ah, thanks! I wasn't aware of the package settings function of ST. That works pretty great for me.
